chore-turn/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

    resources :households do
      resources :chores do
        resources :users
      end
    end

    root 'welcome#index'
end

chore-turn/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

chore-turn/app/models/assignment_chore.rb
class AssignmentChore < ApplicationRecord

  belongs_to :user
  belongs_to :chore
end

chore-turn/app/models/chore.rb
class Chore < ApplicationRecord
  validates :name, :date, presence: true

  belongs_to :household
  has_many :assignment_chores
end

chore-turn/app/models/household.rb
class Household < ApplicationRecord
  validates :name, :address, :city, :state, :zip_code, presence: true
  validates :zip_code, numericality: { equals_to: 5 }

  has_many :chores
  has_many :household_users
  has_many :users, through: :household_users
end

chore-turn/app/models/household_user.rb
class HouseholdUser < ApplicationRecord
  belongs_to :user
  belongs_to :household
end

chore-turn/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :first_name, :last_name, :username, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :assignment_chores
  has_many :household_users
  has_many :chores, through: :assignment_chores
  has_many :households, through: :household_users
end

chore-turn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end

end

chore-turn/app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  def index
    @chores = Chore.all
  end

  def show
    @chore = Chore.find(params[:id])
  end

  def new
    @chore = Chore.new
  end

  def edit
    @chore = Chore.find(params[:id])
  end

  def create
    @chore = Chore.new(chore_params)
    if @chore.save
      redirect_to @chore
    else
      render 'new'
    end
  end

  def update
    @chore = Chore.find(params[:id])
    if @chore.update(chore_params)
      redirect_to @chore
    else
      render 'edit'
    end
  end

  def destroy
  @chore = Chore.find(params[:id])
  @chore.destroy

  redirect_to chores_path
end

  private
  def chore_params
    params.require(:chore).permit(:id, :name, :duration, :status, :date, :household_id)
  end
end

chore-turn/app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  def index
    @households = Household.all
  end

  def show
    @household = Household.find(params[:id])
  end

  def new
    @household = Household.new
  end

  def edit
    @household = Household.find(params[:id])
  end

  def create
    @household = Household.new(household_params)
    if @household.save
      redirect_to @household
    else
      render 'new'
    end
  end

  def update
    @household = Household.find(params[:id])
    if @household.update(household_params)
      redirect_to @household
    else
      render 'edit'
    end
  end

  def destroy
  @household = Household.find(params[:id])
  @household.destroy

  redirect_to households_path
end

  private
  def household_params
    params.require(:household).permit(:id, :name, :home_address)
  end
end

chore-turn/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index


  end
end

chore-turn/app/helpers/application_helper.rb
module ApplicationHelper
end

chore-turn/app/helpers/chores_helper.rb
module ChoresHelper
end

chore-turn/app/helpers/household_helper.rb
module HouseholdHelper
end

chore-turn/app/helpers/households_helper.rb
module HouseholdsHelper
end

chore-turn/app/helpers/welcome_helper.rb
module WelcomeHelper
end

chore-turn/app/views/chores/_form.html.erb
<%= form_with model: @chore do |form| %>

<% if @chore.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@chore.errors.count, "error") %> prohibited
      this chore from being saved:
    </h2>
    <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :household %><br>
    <%= form.text_field :household_id %>
  </p>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :duration %><br>
    <%= form.text_field :duration %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.text_field :status %>
  </p>

  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

chore-turn/app/views/chores/edit.html.erb
<h1> Edit a Chore</h1>


<%= render 'form' %>
<%= link_to 'Back', chores_path %>

chore-turn/app/views/chores/index.html.erb
<h1>Chore List</h1>

<%= link_to 'New chore', new_chore_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Date</th>
    <th>Status</th>
  </tr>

  <% @chores.each do |chore| %>
    <tr>
      <td><%= chore.name %></td><br>
      <td><%= chore.duration %></td><br>
      <td><%= chore.date %></td><br>
      <td><%= chore.status %></td><br>

      <td><%= link_to 'My Chores', controller: 'chores' %></td>
      <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
      <td><%= link_to 'Destroy', article_path(chore),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

chore-turn/app/views/chores/new.html.erb
<h1> Chores</h1>


<%= render 'form' %>
<%= link_to 'Back', chores_path %>

chore-turn/app/views/chores/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @chore.name%>
</p>

<p>
  <strong>Duration:</strong>
  <%= @chore.duration %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

chore-turn/app/views/households/_form.html.erb
<%= form_with(model: household, local: true) do |form| %>
  <% if household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% household.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

chore-turn/app/views/households/edit.html.erb
<h1>Editing Household</h1>

<%= render 'form', household: @household %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

chore-turn/app/views/households/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Households</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @households.each do |household| %>
      <tr>
        <td><%= link_to 'Show', household %></td>
        <td><%= link_to 'Edit', edit_household_path(household) %></td>
        <td><%= link_to 'Destroy', household, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Household', new_household_path %>

chore-turn/app/views/households/new.html.erb
<h1>New Household</h1>

<%= render 'form', household: @household %>

<%= link_to 'Back', households_path %>

chore-turn/app/views/households/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_household_path(@household) %> |
<%= link_to 'Back', households_path %>

chore-turn/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChoreTurn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <%= render 'shared/alerts' %>
    <%= yield %>
  </body>
</html>

chore-turn/app/views/shared/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

chore-turn/app/views/welcome/index.html.erb
<h1>Chore Turn!</h1>

<td><%= link_to 'Assign Chores to Household', controller: 'households' %></td>